sudo: false
language: C
services:
  - docker

cache:
    directories:
      - $HOME/.cache

git:
    depth: 100500

env:
    global:
      - PRODUCT=tarantool-vshard
    matrix:
      - OS=el DIST=6
      - OS=el DIST=7
      - OS=fedora DIST=26
      - OS=fedora DIST=27
      - OS=fedora DIST=28
      - OS=fedora DIST=29
      - OS=fedora DIST=30
      - OS=ubuntu DIST=trusty
      - OS=ubuntu DIST=xenial
      - OS=ubuntu DIST=bionic
      - OS=ubuntu DIST=disco
      - OS=debian DIST=jessie
      - OS=debian DIST=stretch
      - OS=debian DIST=buster

script:
  - git describe --long
  - git clone https://github.com/packpack/packpack.git packpack
  - packpack/packpack -e PACKPACK_GIT_SOURCEDIR=/source/

before_deploy:
  - ls -l build/

deploy:
  # Deploy packages to PackageCloud from master branch
  - provider: packagecloud
    username: tarantool
    repository: "1_9"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{deb,rpm,dsc}
    skip_cleanup: true
    on:
      branch: "master"
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"
  - provider: packagecloud
    username: tarantool
    repository: "1_10"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{deb,rpm,dsc}
    skip_cleanup: true
    on:
      branch: "master"
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"
  - provider: packagecloud
    username: tarantool
    repository: "2x"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{deb,rpm,dsc}
    skip_cleanup: true
    on:
      branch: "master"
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"
  - provider: packagecloud
    username: tarantool
    repository: "2_2"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{deb,rpm,dsc}
    skip_cleanup: true
    on:
      branch: "master"
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"
  - provider: packagecloud
    username: tarantool
    repository: "2_3"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{deb,rpm,dsc}
    skip_cleanup: true
    on:
      branch: "master"
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"
  # Deploy packages to PackageCloud from tags
  # see:
  #   * https://github.com/tarantool/tarantool/issues/3745
  #   * https://github.com/travis-ci/travis-ci/issues/7780#issuecomment-302389370
  - provider: packagecloud
    username: tarantool
    repository: "1_9"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{deb,rpm,dsc}
    skip_cleanup: true
    on:
      tags: true
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"
  - provider: packagecloud
    username: tarantool
    repository: "1_10"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{deb,rpm,dsc}
    skip_cleanup: true
    on:
      tags: true
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"
  - provider: packagecloud
    username: tarantool
    repository: "2x"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{deb,rpm,dsc}
    skip_cleanup: true
    on:
      tags: true
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"
  - provider: packagecloud
    username: tarantool
    repository: "2_2"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{deb,rpm,dsc}
    skip_cleanup: true
    on:
      tags: true
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"
  - provider: packagecloud
    username: tarantool
    repository: "2_3"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{deb,rpm,dsc}
    skip_cleanup: true
    on:
      tags: true
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"

notifications:
  email:
    recipients:
      - build@tarantool.org
    on_success: change
    on_failure: always
